env:
  ARK_REPO: "posit-dev/ark"
  # Causes ark to install the kernel spec to this dir
  KERNEL_DIR: "./kernels/frozen"
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      # https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/run-job-variations
      matrix:
        # ark_version: [0.1.216, latest]
        ark_version: [0.1.216]
        include:
          - os: ubuntu-latest
            asset-pattern: '*-linux-x64.zip'
          # - os: windows-latest
          #   asset-pattern: '*-windows-x64.zip'
          # - os: macos-latest
          #   asset-pattern: '*-darwin-universal.zip'

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - name: Download Ark for "${{ matrix.os }}"
        id: release_data
        # https://github.com/marketplace/actions/github-release-data
        uses: KevinRohn/github-full-release-data@v2
        with:
          repository: ${{ env.ARK_REPO }}
          version: ${{ matrix.ark_version }}
          asset-file: ${{ matrix.asset-pattern }}
          asset-output: ${{ env.KERNEL_DIR }}

      - name: Install Ark
        run: |
          unzip $KERNEL_DIR/*.zip
          $KERNEL_DIR/ark --install

      - name: Cargo test
        run: cargo test
